### ISSUE TITLE
add `dry-run` feature

### ISSUE THREAD

**Issue by celestialorb** [ugognw/mypy-upgrade#14]
I'd like to be able to use `mypy-upgrade` with a `dry-run` feature (in both the CLI as well as the API) as I'd like the option to report what changes would be made _before_ actually writing those changes back to the source file(s).

**Comment by ugognw** [comment]
Thanks for the suggestion! I've drafted a working version over at [logging](https://github.com/ugognw/mypy-upgrade/tree/logging).

**Comment by ugognw** [comment]
this is added in v0.0.1b6
