### ISSUE TITLE
add error selection feature

### ISSUE THREAD

**Issue by celestialorb** [ugognw/mypy-upgrade#15]
I'd like the ability to select which `mypy` errors I want to fix, in both the CLI as well as the API. This is primarily driven by the want to iteratively suppress errors, rather than suppressing all of them at once. This could probably be done by adding a multiple flag (`--fix-error <name of mypy error>`) to the CLI and an `Optional[List[str]]` input to the API. By default, if not supplied, it could fix all errors.

**Comment by ugognw** [comment]
Thanks for the suggestion! I've drafted a working version over at [logging](https://github.com/ugognw/mypy-upgrade/tree/logging).

**Comment by ugognw** [comment]
this is added in v0.0.1b6
